DATABASE_MODULES = [
    'aerospike_migrations', 'influxdb_database', 'influxdb_query', 'influxdb_retention_policy', 'influxdb_user',
    'influxdb_write', 'elasticsearch_plugin', 'kibana_plugin', 'redis', 'riak', 'mongodb_parameter',
    'mongodb_replicaset', 'mongodb_shard', 'mongodb_user', 'mssql_db', 'mysql_db', 'mysql_replication',
    'mysql_user', 'mysql_variables', 'postgresql_db', 'postgresql_ext', 'postgresql_idx', 'postgresql_info',
    'postgresql_lang', 'postgresql_membership', 'postgresql_owner', 'postgresql_pg_hba', 'postgresql_ping',
    'postgresql_privs', 'postgresql_query', 'postgresql_schema', 'postgresql_set', 'postgresql_slot',
    'postgresql_table', 'postgresql_tablespace', 'postgresql_user', 'proxysql_backend_servers',
    'proxysql_global_variables', 'proxysql_manage_config', 'proxysql_mysql_users', 'proxysql_query_rules',
    'proxysql_replication_hostgroups', 'proxysql_scheduler', 'vertica_configuration', 'vertica_facts',
    'vertica_role', 'vertica_schema', 'vertica_user'
]

FILE_MODULES = [
    'acl', 'archive', 'assemble', 'blockinfile', 'copy', 'fetch', 'file', 'find', 'ini_file', 'iso_extract',
    'lineinfile', 'patch', 'read_csv', 'replace', 'stat', 'synchronize', 'tempfile', 'template', 'unarchive',
    'xattr', 'xml'
]

STORAGE_MODULES = [
    'emc_vnx_sg_member', 'gluster_heal_facts', 'gluster_peer', 'gluster_volume', 'ss_3par_cpg', 'ibm_sa_domain',
    'ibm_sa_host', 'ibm_sa_host_ports', 'ibm_sa_pool', 'ibm_sa_vol', 'ibm_sa_vol_map', 'infini_export',
    'infini_export_client', 'infini_fs', 'infini_host', 'infini_pool', 'infini_vol', 'na_cdot_aggregate',
    'na_cdot_license', 'na_cdot_lun', 'na_cdot_qtree', 'na_cdot_svm', 'na_cdot_user', 'na_cdot_user_role',
    'na_cdot_volume', 'na_elementsw_access_group', 'na_elementsw_account', 'na_elementsw_admin_users',
    'na_elementsw_backup', 'na_elementsw_check_connections', 'na_elementsw_cluster', 'na_elementsw_cluster_config',
    'na_elementsw_cluster_pair', 'na_elementsw_cluster_snmp', 'na_elementsw_drive', 'na_elementsw_initiators',
    'na_elementsw_ldap', 'na_elementsw_network_interfaces', 'na_elementsw_node', 'na_elementsw_snapshot',
    'na_elementsw_snapshot_restore', 'na_elementsw_snapshot_schedule', 'na_elementsw_vlan', 'na_elementsw_volume',
    'na_elementsw_volume_clone', 'na_elementsw_volume_pair', 'na_ontap_aggregate', 'na_ontap_autosupport',
    'na_ontap_broadcast_domain', 'na_ontap_broadcast_domain_ports', 'na_ontap_cg_snapshot', 'na_ontap_cifs',
    'na_ontap_cifs_acl', 'na_ontap_cifs_server', 'na_ontap_cluster', 'na_ontap_cluster_ha', 'na_ontap_cluster_peer',
    'na_ontap_command', 'na_ontap_disks', 'na_ontap_dns', 'na_ontap_export_policy', 'na_ontap_export_policy_rule',
    'na_ontap_fcp', 'na_ontap_firewall_policy', 'na_ontap_flexcache', 'na_ontap_gather_facts', 'na_ontap_igroup',
    'na_ontap_igroup_initiator', 'na_ontap_interface', 'na_ontap_iscsi', 'na_ontap_job_schedule',
    'na_ontap_license', 'na_ontap_lun', 'na_ontap_lun_copy', 'na_ontap_lun_map', 'na_ontap_motd',
    'na_ontap_net_ifgrp', 'na_ontap_net_port', 'na_ontap_net_routes', 'na_ontap_net_subnet', 'na_ontap_net_vlan',
    'na_ontap_nfs', 'na_ontap_node', 'na_ontap_ntp', 'na_ontap_nvme', 'na_ontap_nvme_namespace',
    'na_ontap_nvme_subsystem', 'na_ontap_portset', 'na_ontap_qos_policy_group', 'na_ontap_qtree', 'na_ontap_quotas',
    'na_ontap_security_key_manager', 'na_ontap_service_processor_network', 'na_ontap_snapmirror',
    'na_ontap_snapshot', 'na_ontap_snapshot_policy', 'na_ontap_snmp', 'na_ontap_software_update', 'na_ontap_svm',
    'na_ontap_svm_options', 'na_ontap_ucadapter', 'na_ontap_unix_group', 'na_ontap_unix_user', 'na_ontap_user',
    'na_ontap_user_role', 'na_ontap_volume', 'na_ontap_volume_clone', 'na_ontap_vscan_on_access_policy',
    'na_ontap_vscan_on_demand_task', 'na_ontap_vscan_scanner_pool', 'na_ontap_vserver_peer', 'netapp_e_alerts',
    'netapp_e_amg', 'netapp_e_amg_role', 'netapp_e_amg_sync', 'netapp_e_asup', 'netapp_e_auditlog', 'netapp_e_auth',
    'netapp_e_facts', 'netapp_e_flashcache', 'netapp_e_global', 'netapp_e_host', 'netapp_e_hostgroup',
    'netapp_e_iscsi_interface', 'netapp_e_iscsi_target', 'netapp_e_ldap', 'netapp_e_lun_mapping',
    'netapp_e_mgmt_interface', 'netapp_e_snapshot_group', 'netapp_e_snapshot_images', 'netapp_e_snapshot_volume',
    'netapp_e_storage_system', 'netapp_e_storagepool', 'netapp_e_syslog', 'netapp_e_volume', 'netapp_e_volume_copy',
    'sf_account_manager', 'sf_check_connections', 'sf_snapshot_schedule_manager', 'sf_volume_access_group_manager',
    'sf_volume_manager', 'purefa_dns', 'purefa_ds', 'purefa_dsrole', 'purefa_facts', 'purefa_hg', 'purefa_host',
    'purefa_ntp', 'purefa_offload', 'purefa_pg', 'purefa_pgsnap', 'purefa_ra', 'purefa_snap', 'purefa_user',
    'purefa_volume', 'purefb_bucket', 'purefb_ds', 'purefb_dsrole', 'purefb_facts', 'purefb_fs', 'purefb_network',
    'purefb_s3acc', 'purefb_s3user', 'purefb_snap', 'purefb_subnet', 'vexata_volume', 'zfs', 'zfs_delegate_admin',
    'zfs_facts', 'zpool_facts'
]

NETWORK_MODULES = [
    'a10_server', 'a10_server_axapi3', 'a10_service_group', 'a10_virtual_server', 'aci_aaa_user',
    'aci_aaa_user_certificate', 'aci_access_port_block_to_access_port',
    'aci_access_port_to_interface_policy_leaf_profile', 'aci_access_sub_port_block_to_access_port', 'aci_aep',
    'aci_aep_to_domain', 'aci_ap', 'aci_bd', 'aci_bd_subnet', 'aci_bd_to_l3out', 'aci_config_rollback',
    'aci_config_snapshot', 'aci_contract', 'aci_contract_subject', 'aci_contract_subject_to_filter', 'aci_domain',
    'aci_domain_to_encap_pool', 'aci_domain_to_vlan_pool', 'aci_encap_pool', 'aci_encap_pool_range', 'aci_epg',
    'aci_epg_monitoring_policy', 'aci_epg_to_contract', 'aci_epg_to_domain', 'aci_fabric_node',
    'aci_fabric_scheduler', 'aci_filter', 'aci_filter_entry', 'aci_firmware_group', 'aci_firmware_group_node',
    'aci_firmware_policy', 'aci_firmware_source', 'aci_interface_policy_fc', 'aci_interface_policy_l2',
    'aci_interface_policy_leaf_policy_group', 'aci_interface_policy_leaf_profile', 'aci_interface_policy_lldp',
    'aci_interface_policy_mcp', 'aci_interface_policy_ospf', 'aci_interface_policy_port_channel',
    'aci_interface_policy_port_security', 'aci_interface_selector_to_switch_policy_leaf_profile', 'aci_l3out',
    'aci_l3out_route_tag_policy', 'aci_maintenance_group', 'aci_maintenance_group_node', 'aci_maintenance_policy',
    'aci_rest', 'aci_static_binding_to_epg', 'aci_switch_leaf_selector', 'aci_switch_policy_leaf_profile',
    'aci_switch_policy_vpc_protection_group', 'aci_taboo_contract', 'aci_tenant', 'aci_tenant_action_rule_profile',
    'aci_tenant_ep_retention_policy', 'aci_tenant_span_dst_group', 'aci_tenant_span_src_group',
    'aci_tenant_span_src_group_to_dst_group', 'aci_vlan_pool', 'aci_vlan_pool_encap_block', 'aci_vrf', 'mso_label',
    'mso_role', 'mso_schema', 'mso_schema_site', 'mso_schema_site_anp', 'mso_schema_site_anp_epg',
    'mso_schema_site_anp_epg_staticleaf', 'mso_schema_site_anp_epg_staticport', 'mso_schema_site_anp_epg_subnet',
    'mso_schema_site_bd', 'mso_schema_site_bd_l3out', 'mso_schema_site_bd_subnet', 'mso_schema_site_vrf',
    'mso_schema_site_vrf_region', 'mso_schema_site_vrf_region_cidr', 'mso_schema_site_vrf_region_cidr_subnet',
    'mso_schema_template', 'mso_schema_template_anp', 'mso_schema_template_anp_epg',
    'mso_schema_template_anp_epg_contract', 'mso_schema_template_anp_epg_subnet', 'mso_schema_template_bd',
    'mso_schema_template_bd_subnet', 'mso_schema_template_contract_filter', 'mso_schema_template_deploy',
    'mso_schema_template_externalepg', 'mso_schema_template_filter_entry', 'mso_schema_template_l3out',
    'mso_schema_template_vrf', 'mso_site', 'mso_tenant', 'mso_user', 'aireos_command', 'aireos_config',
    'aos_asn_pool', 'aos_blueprint', 'aos_blueprint_param', 'aos_blueprint_virtnet', 'aos_device',
    'aos_external_router', 'aos_ip_pool', 'aos_logical_device', 'aos_logical_device_map', 'aos_login',
    'aos_rack_type', 'aos_template', 'aruba_command', 'aruba_config', 'asa_acl', 'asa_command', 'asa_config',
    'asa_og', 'avi_actiongroupconfig', 'avi_alertconfig', 'avi_alertemailconfig', 'avi_alertscriptconfig',
    'avi_alertsyslogconfig', 'avi_analyticsprofile', 'avi_api_session', 'avi_api_version',
    'avi_applicationpersistenceprofile', 'avi_applicationprofile', 'avi_authprofile', 'avi_autoscalelaunchconfig',
    'avi_backup', 'avi_backupconfiguration', 'avi_certificatemanagementprofile', 'avi_cloud',
    'avi_cloudconnectoruser', 'avi_cloudproperties', 'avi_cluster', 'avi_clusterclouddetails',
    'avi_controllerproperties', 'avi_customipamdnsprofile', 'avi_dnspolicy', 'avi_errorpagebody',
    'avi_errorpageprofile', 'avi_gslb', 'avi_gslbapplicationpersistenceprofile', 'avi_gslbgeodbprofile',
    'avi_gslbhealthmonitor', 'avi_gslbservice', 'avi_gslbservice_patch_member', 'avi_hardwaresecuritymodulegroup',
    'avi_healthmonitor', 'avi_httppolicyset', 'avi_ipaddrgroup', 'avi_ipamdnsproviderprofile', 'avi_l4policyset',
    'avi_microservicegroup', 'avi_network', 'avi_networkprofile', 'avi_networksecuritypolicy', 'avi_pkiprofile',
    'avi_pool', 'avi_poolgroup', 'avi_poolgroupdeploymentpolicy', 'avi_prioritylabels', 'avi_role', 'avi_scheduler',
    'avi_seproperties', 'avi_serverautoscalepolicy', 'avi_serviceengine', 'avi_serviceenginegroup',
    'avi_snmptrapprofile', 'avi_sslkeyandcertificate', 'avi_sslprofile', 'avi_stringgroup',
    'avi_systemconfiguration', 'avi_tenant', 'avi_trafficcloneprofile', 'avi_useraccount', 'avi_useraccountprofile',
    'avi_virtualservice', 'avi_vrfcontext', 'avi_vsdatascriptset', 'avi_vsvip', 'avi_wafpolicy', 'avi_wafprofile',
    'avi_webhook', 'bcf_switch', 'bigmon_chain', 'bigmon_policy', 'checkpoint_access_layer_facts',
    'checkpoint_access_rule', 'checkpoint_access_rule_facts', 'checkpoint_host', 'checkpoint_host_facts',
    'checkpoint_object_facts', 'checkpoint_run_script', 'checkpoint_session', 'checkpoint_task_facts',
    'cli_command', 'cli_config', 'ce_aaa_server', 'ce_aaa_server_host', 'ce_acl', 'ce_acl_advance',
    'ce_acl_interface', 'ce_bfd_global', 'ce_bfd_session', 'ce_bfd_view', 'ce_bgp', 'ce_bgp_af', 'ce_bgp_neighbor',
    'ce_bgp_neighbor_af', 'ce_command', 'ce_config', 'ce_dldp', 'ce_dldp_interface', 'ce_eth_trunk',
    'ce_evpn_bd_vni', 'ce_evpn_bgp', 'ce_evpn_bgp_rr', 'ce_evpn_global', 'ce_facts', 'ce_file_copy',
    'ce_info_center_debug', 'ce_info_center_global', 'ce_info_center_log', 'ce_info_center_trap', 'ce_interface',
    'ce_interface_ospf', 'ce_ip_interface', 'ce_link_status', 'ce_mlag_config', 'ce_mlag_interface', 'ce_mtu',
    'ce_netconf', 'ce_netstream_aging', 'ce_netstream_export', 'ce_netstream_global', 'ce_netstream_template',
    'ce_ntp', 'ce_ntp_auth', 'ce_ospf', 'ce_ospf_vrf', 'ce_reboot', 'ce_rollback', 'ce_sflow', 'ce_snmp_community',
    'ce_snmp_contact', 'ce_snmp_location', 'ce_snmp_target_host', 'ce_snmp_traps', 'ce_snmp_user', 'ce_startup',
    'ce_static_route', 'ce_stp', 'ce_switchport', 'ce_vlan', 'ce_vrf', 'ce_vrf_af', 'ce_vrf_interface', 'ce_vrrp',
    'ce_vxlan_arp', 'ce_vxlan_gateway', 'ce_vxlan_global', 'ce_vxlan_tunnel', 'ce_vxlan_vap', 'cv_server_provision',
    'cnos_backup', 'cnos_banner', 'cnos_bgp', 'cnos_command', 'cnos_conditional_command',
    'cnos_conditional_template', 'cnos_config', 'cnos_factory', 'cnos_facts', 'cnos_image', 'cnos_interface',
    'cnos_l2_interface', 'cnos_l3_interface', 'cnos_linkagg', 'cnos_lldp', 'cnos_logging', 'cnos_reload',
    'cnos_rollback', 'cnos_save', 'cnos_showrun', 'cnos_static_route', 'cnos_system', 'cnos_template', 'cnos_user',
    'cnos_vlag', 'cnos_vlan', 'cnos_vrf', 'nclu', 'dellos10_command', 'dellos10_config', 'dellos10_facts',
    'dellos6_command', 'dellos6_config', 'dellos6_facts', 'dellos9_command', 'dellos9_config', 'dellos9_facts',
    'edgeos_command', 'edgeos_config', 'edgeos_facts', 'edgeswitch_facts', 'edgeswitch_vlan', 'enos_command',
    'enos_config', 'enos_facts', 'eos_banner', 'eos_bgp', 'eos_command', 'eos_config', 'eos_eapi', 'eos_facts',
    'eos_interface', 'eos_l2_interface', 'eos_l3_interface', 'eos_linkagg', 'eos_lldp', 'eos_logging',
    'eos_static_route', 'eos_system', 'eos_user', 'eos_vlan', 'eos_vrf', 'exos_command', 'exos_config',
    'exos_facts', 'bigip_apm_policy_fetch', 'bigip_apm_policy_import', 'bigip_appsvcs_extension',
    'bigip_asm_policy', 'bigip_asm_policy_fetch', 'bigip_asm_policy_import', 'bigip_asm_policy_manage',
    'bigip_asm_policy_server_technology', 'bigip_asm_policy_signature_set', 'bigip_cli_alias', 'bigip_cli_script',
    'bigip_command', 'bigip_config', 'bigip_configsync_action', 'bigip_data_group', 'bigip_device_auth',
    'bigip_device_auth_ldap', 'bigip_device_connectivity', 'bigip_device_dns', 'bigip_device_facts',
    'bigip_device_group', 'bigip_device_group_member', 'bigip_device_ha_group', 'bigip_device_httpd',
    'bigip_device_license', 'bigip_device_ntp', 'bigip_device_sshd', 'bigip_device_syslog',
    'bigip_device_traffic_group', 'bigip_device_trust', 'bigip_dns_cache_resolver', 'bigip_dns_nameserver',
    'bigip_dns_resolver', 'bigip_dns_zone', 'bigip_facts', 'bigip_file_copy', 'bigip_firewall_address_list',
    'bigip_firewall_dos_profile', 'bigip_firewall_dos_vector', 'bigip_firewall_global_rules',
    'bigip_firewall_policy', 'bigip_firewall_port_list', 'bigip_firewall_rule', 'bigip_firewall_rule_list',
    'bigip_gtm_datacenter', 'bigip_gtm_facts', 'bigip_gtm_global', 'bigip_gtm_monitor_bigip',
    'bigip_gtm_monitor_external', 'bigip_gtm_monitor_firepass', 'bigip_gtm_monitor_http', 'bigip_gtm_monitor_https',
    'bigip_gtm_monitor_tcp', 'bigip_gtm_monitor_tcp_half_open', 'bigip_gtm_pool', 'bigip_gtm_pool_member',
    'bigip_gtm_server', 'bigip_gtm_topology_record', 'bigip_gtm_topology_region', 'bigip_gtm_virtual_server',
    'bigip_gtm_wide_ip', 'bigip_hostname', 'bigip_iapp_service', 'bigip_iapp_template', 'bigip_ike_peer',
    'bigip_imish_config', 'bigip_ipsec_policy', 'bigip_irule', 'bigip_log_destination', 'bigip_log_publisher',
    'bigip_lx_package', 'bigip_management_route', 'bigip_monitor_dns', 'bigip_monitor_external',
    'bigip_monitor_gateway_icmp', 'bigip_monitor_http', 'bigip_monitor_https', 'bigip_monitor_ldap',
    'bigip_monitor_snmp_dca', 'bigip_monitor_tcp', 'bigip_monitor_tcp_echo', 'bigip_monitor_tcp_half_open',
    'bigip_monitor_udp', 'bigip_node', 'bigip_partition', 'bigip_password_policy', 'bigip_policy',
    'bigip_policy_rule', 'bigip_pool', 'bigip_pool_member', 'bigip_profile_analytics', 'bigip_profile_client_ssl',
    'bigip_profile_dns', 'bigip_profile_fastl4', 'bigip_profile_http', 'bigip_profile_http2',
    'bigip_profile_http_compression', 'bigip_profile_oneconnect', 'bigip_profile_persistence_cookie',
    'bigip_profile_persistence_src_addr', 'bigip_profile_server_ssl', 'bigip_profile_tcp', 'bigip_profile_udp',
    'bigip_provision', 'bigip_qkview', 'bigip_remote_role', 'bigip_remote_syslog', 'bigip_routedomain',
    'bigip_selfip', 'bigip_service_policy', 'bigip_smtp', 'bigip_snat_pool', 'bigip_snmp', 'bigip_snmp_community',
    'bigip_snmp_trap', 'bigip_software_image', 'bigip_software_install', 'bigip_software_update',
    'bigip_ssl_certificate', 'bigip_ssl_key', 'bigip_ssl_ocsp', 'bigip_static_route', 'bigip_sys_daemon_log_tmm',
    'bigip_sys_db', 'bigip_sys_global', 'bigip_timer_policy', 'bigip_traffic_selector', 'bigip_trunk',
    'bigip_tunnel', 'bigip_ucs', 'bigip_ucs_fetch', 'bigip_user', 'bigip_vcmp_guest', 'bigip_virtual_address',
    'bigip_virtual_server', 'bigip_vlan', 'bigip_wait', 'bigiq_application_fasthttp',
    'bigiq_application_fastl4_tcp', 'bigiq_application_fastl4_udp', 'bigiq_application_http',
    'bigiq_application_https_offload', 'bigiq_application_https_waf', 'bigiq_device_discovery',
    'bigiq_device_facts', 'bigiq_regkey_license', 'bigiq_regkey_license_assignment', 'bigiq_regkey_pool',
    'bigiq_utility_license', 'bigiq_utility_license_assignment', 'net_get', 'net_put', 'fmgr_device',
    'fmgr_device_config', 'fmgr_device_group', 'fmgr_device_provision_template', 'fmgr_fwobj_address',
    'fmgr_fwobj_ippool', 'fmgr_fwobj_ippool6', 'fmgr_fwobj_service', 'fmgr_fwobj_vip', 'fmgr_fwpol_ipv4',
    'fmgr_fwpol_package', 'fmgr_ha', 'fmgr_provisioning', 'fmgr_query', 'fmgr_script', 'fmgr_secprof_appctrl',
    'fmgr_secprof_av', 'fmgr_secprof_dns', 'fmgr_secprof_ips', 'fmgr_secprof_profile_group', 'fmgr_secprof_proxy',
    'fmgr_secprof_spam', 'fmgr_secprof_ssl_ssh', 'fmgr_secprof_voip', 'fmgr_secprof_waf', 'fmgr_secprof_wanopt',
    'fmgr_secprof_web', 'fortios_address', 'fortios_antivirus_heuristic', 'fortios_antivirus_profile',
    'fortios_antivirus_quarantine', 'fortios_antivirus_settings', 'fortios_application_custom',
    'fortios_application_group', 'fortios_application_list', 'fortios_application_name',
    'fortios_application_rule_settings', 'fortios_authentication_rule', 'fortios_authentication_scheme',
    'fortios_authentication_setting', 'fortios_config', 'fortios_dlp_filepattern', 'fortios_dlp_fp_doc_source',
    'fortios_dlp_fp_sensitivity', 'fortios_dlp_sensor', 'fortios_dlp_settings', 'fortios_dnsfilter_domain_filter',
    'fortios_dnsfilter_profile', 'fortios_endpoint_control_client', 'fortios_endpoint_control_forticlient_ems',
    'fortios_endpoint_control_forticlient_registration_sync', 'fortios_endpoint_control_profile',
    'fortios_endpoint_control_settings', 'fortios_extender_controller_extender', 'fortios_firewall_address',
    'fortios_firewall_address6', 'fortios_firewall_address6_template', 'fortios_firewall_addrgrp',
    'fortios_firewall_addrgrp6', 'fortios_firewall_auth_portal', 'fortios_firewall_central_snat_map',
    'fortios_firewall_dnstranslation', 'fortios_firewall_DoS_policy', 'fortios_firewall_DoS_policy6',
    'fortios_firewall_identity_based_route', 'fortios_firewall_interface_policy',
    'fortios_firewall_interface_policy6', 'fortios_firewall_internet_service',
    'fortios_firewall_internet_service_custom', 'fortios_firewall_internet_service_group',
    'fortios_firewall_ip_translation', 'fortios_firewall_ipmacbinding_setting',
    'fortios_firewall_ipmacbinding_table', 'fortios_firewall_ippool', 'fortios_firewall_ippool6',
    'fortios_firewall_ipv6_eh_filter', 'fortios_firewall_ldb_monitor', 'fortios_firewall_local_in_policy',
    'fortios_firewall_local_in_policy6', 'fortios_firewall_multicast_address',
    'fortios_firewall_multicast_address6', 'fortios_firewall_multicast_policy',
    'fortios_firewall_multicast_policy6', 'fortios_firewall_policy', 'fortios_firewall_policy46',
    'fortios_firewall_policy6', 'fortios_firewall_policy64', 'fortios_firewall_profile_group',
    'fortios_firewall_profile_protocol_options', 'fortios_firewall_proxy_address', 'fortios_firewall_proxy_addrgrp',
    'fortios_firewall_proxy_policy', 'fortios_firewall_schedule_group', 'fortios_firewall_schedule_onetime',
    'fortios_firewall_schedule_recurring', 'fortios_firewall_service_category', 'fortios_firewall_service_custom',
    'fortios_firewall_service_group', 'fortios_firewall_shaper_per_ip_shaper',
    'fortios_firewall_shaper_traffic_shaper', 'fortios_firewall_shaping_policy', 'fortios_firewall_shaping_profile',
    'fortios_firewall_sniffer', 'fortios_firewall_ssh_host_key', 'fortios_firewall_ssh_local_ca',
    'fortios_firewall_ssh_local_key', 'fortios_firewall_ssh_setting', 'fortios_firewall_ssl_server',
    'fortios_firewall_ssl_setting', 'fortios_firewall_ssl_ssh_profile', 'fortios_firewall_ttl_policy',
    'fortios_firewall_vip', 'fortios_firewall_vip46', 'fortios_firewall_vip6', 'fortios_firewall_vip64',
    'fortios_firewall_vipgrp', 'fortios_firewall_vipgrp46', 'fortios_firewall_vipgrp6', 'fortios_firewall_vipgrp64',
    'fortios_firewall_wildcard_fqdn_custom', 'fortios_firewall_wildcard_fqdn_group', 'fortios_ftp_proxy_explicit',
    'fortios_icap_profile', 'fortios_icap_server', 'fortios_ips_custom', 'fortios_ips_decoder',
    'fortios_ips_global', 'fortios_ips_rule', 'fortios_ips_rule_settings', 'fortios_ips_sensor',
    'fortios_ips_settings', 'fortios_ipv4_policy', 'fortios_log_custom_field', 'fortios_log_disk_filter',
    'fortios_log_disk_setting', 'fortios_log_eventfilter', 'fortios_log_fortianalyzer2_filter',
    'fortios_log_fortianalyzer2_setting', 'fortios_log_fortianalyzer3_filter', 'fortios_log_fortianalyzer3_setting',
    'fortios_log_fortianalyzer_filter', 'fortios_log_fortianalyzer_override_filter',
    'fortios_log_fortianalyzer_override_setting', 'fortios_log_fortianalyzer_setting',
    'fortios_log_fortiguard_filter', 'fortios_log_fortiguard_override_filter',
    'fortios_log_fortiguard_override_setting', 'fortios_log_fortiguard_setting', 'fortios_log_gui_display',
    'fortios_log_memory_filter', 'fortios_log_memory_global_setting', 'fortios_log_memory_setting',
    'fortios_log_null_device_filter', 'fortios_log_null_device_setting', 'fortios_log_setting',
    'fortios_log_syslogd2_filter', 'fortios_log_syslogd2_setting', 'fortios_log_syslogd3_filter',
    'fortios_log_syslogd3_setting', 'fortios_log_syslogd4_filter', 'fortios_log_syslogd4_setting',
    'fortios_log_syslogd_filter', 'fortios_log_syslogd_override_filter', 'fortios_log_syslogd_override_setting',
    'fortios_log_syslogd_setting', 'fortios_log_threat_weight', 'fortios_log_webtrends_filter',
    'fortios_log_webtrends_setting', 'fortios_report_chart', 'fortios_report_dataset', 'fortios_report_layout',
    'fortios_report_setting', 'fortios_report_style', 'fortios_report_theme', 'fortios_router_access_list',
    'fortios_router_auth_path', 'fortios_router_bfd', 'fortios_router_bfd6', 'fortios_router_bgp',
    'fortios_router_multicast', 'fortios_router_multicast6', 'fortios_router_multicast_flow', 'fortios_router_ospf',
    'fortios_router_ospf6', 'fortios_router_policy', 'fortios_router_policy6', 'fortios_router_prefix_list',
    'fortios_router_rip', 'fortios_router_setting', 'fortios_router_static', 'fortios_spamfilter_profile',
    'fortios_ssh_filter_profile', 'fortios_switch_controller_global', 'fortios_switch_controller_lldp_profile',
    'fortios_switch_controller_lldp_settings', 'fortios_switch_controller_mac_sync_settings',
    'fortios_switch_controller_managed_switch', 'fortios_switch_controller_network_monitor_settings',
    'fortios_system_accprofile', 'fortios_system_admin', 'fortios_system_api_user',
    'fortios_system_central_management', 'fortios_system_dhcp_server', 'fortios_system_dns',
    'fortios_system_global', 'fortios_system_interface', 'fortios_system_sdn_connector', 'fortios_system_settings',
    'fortios_system_vdom', 'fortios_system_virtual_wan_link', 'fortios_user_adgrp', 'fortios_user_radius',
    'fortios_user_tacacsplus', 'fortios_voip_profile', 'fortios_vpn_ipsec_concentrator',
    'fortios_vpn_ipsec_forticlient', 'fortios_vpn_ipsec_manualkey', 'fortios_vpn_ipsec_manualkey_interface',
    'fortios_vpn_ipsec_phase1', 'fortios_vpn_ipsec_phase1_interface', 'fortios_vpn_ipsec_phase2',
    'fortios_vpn_ipsec_phase2_interface', 'fortios_vpn_ssl_settings', 'fortios_vpn_ssl_web_portal',
    'fortios_waf_profile', 'fortios_wanopt_profile', 'fortios_wanopt_settings', 'fortios_web_proxy_explicit',
    'fortios_web_proxy_global', 'fortios_web_proxy_profile', 'fortios_webfilter', 'fortios_webfilter_content',
    'fortios_webfilter_content_header', 'fortios_webfilter_fortiguard', 'fortios_webfilter_ftgd_local_cat',
    'fortios_webfilter_ftgd_local_rating', 'fortios_webfilter_ips_urlfilter_cache_setting',
    'fortios_webfilter_ips_urlfilter_setting', 'fortios_webfilter_ips_urlfilter_setting6',
    'fortios_webfilter_override', 'fortios_webfilter_profile', 'fortios_webfilter_search_engine',
    'fortios_webfilter_urlfilter', 'fortios_wireless_controller_global', 'fortios_wireless_controller_setting',
    'fortios_wireless_controller_utm_profile', 'fortios_wireless_controller_vap',
    'fortios_wireless_controller_wids_profile', 'fortios_wireless_controller_wtp',
    'fortios_wireless_controller_wtp_profile', 'frr_bgp', 'frr_facts', 'ftd_configuration', 'ftd_file_download',
    'ftd_file_upload', 'ftd_install', 'dladm_etherstub', 'dladm_iptun', 'dladm_linkprop', 'dladm_vlan',
    'dladm_vnic', 'flowadm', 'ipadm_addr', 'ipadm_addrprop', 'ipadm_if', 'ipadm_ifprop', 'ipadm_prop', 'ig_config',
    'ig_unit_information', 'net_interface', 'net_linkagg', 'net_lldp_interface', 'ios_banner', 'ios_bgp',
    'ios_command', 'ios_config', 'ios_facts', 'ios_interface', 'ios_l2_interface', 'ios_l3_interface',
    'ios_linkagg', 'ios_lldp', 'ios_logging', 'ios_ntp', 'ios_ping', 'ios_static_route', 'ios_system', 'ios_user',
    'ios_vlan', 'ios_vrf', 'iosxr_banner', 'iosxr_bgp', 'iosxr_command', 'iosxr_config', 'iosxr_facts',
    'iosxr_interface', 'iosxr_logging', 'iosxr_netconf', 'iosxr_system', 'iosxr_user', 'ironware_command',
    'ironware_config', 'ironware_facts', 'iap_start_workflow', 'iap_token', 'junos_banner', 'junos_command',
    'junos_config', 'junos_facts', 'junos_interface', 'junos_l2_interface', 'junos_l3_interface', 'junos_linkagg',
    'junos_lldp', 'junos_lldp_interface', 'junos_logging', 'junos_netconf', 'junos_package', 'junos_ping',
    'junos_rpc', 'junos_scp', 'junos_static_route', 'junos_system', 'junos_user', 'junos_vlan', 'junos_vrf',
    'net_l2_interface', 'net_vlan', 'net_l3_interface', 'net_vrf', 'meraki_admin', 'meraki_config_template',
    'meraki_content_filtering', 'meraki_device', 'meraki_mr_l3_firewall', 'meraki_mx_l3_firewall', 'meraki_network',
    'meraki_organization', 'meraki_snmp', 'meraki_ssid', 'meraki_static_route', 'meraki_switchport',
    'meraki_syslog', 'meraki_vlan', 'netact_cm_command', 'netconf_config', 'netconf_get', 'netconf_rpc',
    'netscaler_cs_action', 'netscaler_cs_policy', 'netscaler_cs_vserver', 'netscaler_gslb_service',
    'netscaler_gslb_site', 'netscaler_gslb_vserver', 'netscaler_lb_monitor', 'netscaler_lb_vserver',
    'netscaler_nitro_request', 'netscaler_save_config', 'netscaler_server', 'netscaler_service',
    'netscaler_servicegroup', 'netscaler_ssl_certkey', 'pn_access_list', 'pn_access_list_ip', 'pn_admin_service',
    'pn_admin_session_timeout', 'pn_admin_syslog', 'pn_cluster', 'pn_connection_stats_settings', 'pn_cpu_class',
    'pn_cpu_mgmt_class', 'pn_dhcp_filter', 'pn_dscp_map', 'pn_dscp_map_pri_map', 'pn_igmp_snooping', 'pn_ospf',
    'pn_ospfarea', 'pn_port_config', 'pn_port_cos_bw', 'pn_port_cos_rate_setting', 'pn_prefix_list_network',
    'pn_role', 'pn_show', 'pn_snmp_community', 'pn_snmp_trap_sink', 'pn_snmp_vacm', 'pn_stp', 'pn_stp_port',
    'pn_switch_setup', 'pn_trunk', 'pn_user', 'pn_vflow_table_profile', 'pn_vlag', 'pn_vlan', 'pn_vrouter',
    'pn_vrouter_bgp_network', 'pn_vrouter_interface_ip', 'pn_vrouter_ospf6', 'pn_vrouter_pim_config',
    'pn_vrouterbgp', 'pn_vrouterif', 'pn_vrouterlbif', 'nos_command', 'nos_config', 'nos_facts', 'nso_action',
    'nso_config', 'nso_query', 'nso_show', 'nso_verify', 'nuage_vspk', 'nxos_aaa_server', 'nxos_aaa_server_host',
    'nxos_acl', 'nxos_acl_interface', 'nxos_banner', 'nxos_bgp', 'nxos_bgp_af', 'nxos_bgp_neighbor',
    'nxos_bgp_neighbor_af', 'nxos_command', 'nxos_config', 'nxos_evpn_global', 'nxos_evpn_vni', 'nxos_facts',
    'nxos_feature', 'nxos_file_copy', 'nxos_gir', 'nxos_gir_profile_management', 'nxos_hsrp', 'nxos_igmp',
    'nxos_igmp_interface', 'nxos_igmp_snooping', 'nxos_install_os', 'nxos_interface', 'nxos_interface_ospf',
    'nxos_ip_interface', 'nxos_l2_interface', 'nxos_l3_interface', 'nxos_linkagg', 'nxos_lldp', 'nxos_logging',
    'nxos_ntp', 'nxos_ntp_auth', 'nxos_ntp_options', 'nxos_nxapi', 'nxos_ospf', 'nxos_ospf_vrf',
    'nxos_overlay_global', 'nxos_pim', 'nxos_pim_interface', 'nxos_pim_rp_address', 'nxos_ping', 'nxos_portchannel',
    'nxos_reboot', 'nxos_rollback', 'nxos_rpm', 'nxos_smu', 'nxos_snapshot', 'nxos_snmp_community',
    'nxos_snmp_contact', 'nxos_snmp_host', 'nxos_snmp_location', 'nxos_snmp_traps', 'nxos_snmp_user',
    'nxos_static_route', 'nxos_switchport', 'nxos_system', 'nxos_udld', 'nxos_udld_interface', 'nxos_user',
    'nxos_vlan', 'nxos_vpc', 'nxos_vpc_interface', 'nxos_vrf', 'nxos_vrf_af', 'nxos_vrf_interface', 'nxos_vrrp',
    'nxos_vtp_domain', 'nxos_vtp_password', 'nxos_vtp_version', 'nxos_vxlan_vtep', 'nxos_vxlan_vtep_vni',
    'onyx_bgp', 'onyx_buffer_pool', 'onyx_command', 'onyx_config', 'onyx_facts', 'onyx_igmp', 'onyx_igmp_interface',
    'onyx_igmp_vlan', 'onyx_interface', 'onyx_l2_interface', 'onyx_l3_interface', 'onyx_linkagg', 'onyx_lldp',
    'onyx_lldp_interface', 'onyx_magp', 'onyx_mlag_ipl', 'onyx_mlag_vip', 'onyx_ospf', 'onyx_pfc_interface',
    'onyx_protocol', 'onyx_ptp_global', 'onyx_ptp_interface', 'onyx_vlan', 'onyx_vxlan', 'opx_cps',
    'ordnance_config', 'ordnance_facts', 'openvswitch_bridge', 'openvswitch_db', 'openvswitch_port', 'panos_admin',
    'panos_admpwd', 'panos_cert_gen_ssh', 'panos_check', 'panos_commit', 'panos_dag', 'panos_dag_tags',
    'panos_import', 'panos_interface', 'panos_lic', 'panos_loadcfg', 'panos_match_rule', 'panos_mgtconfig',
    'panos_nat_policy', 'panos_nat_rule', 'panos_object', 'panos_op', 'panos_pg', 'panos_query_rules',
    'panos_restart', 'panos_sag', 'panos_security_policy', 'panos_security_rule', 'panos_set', 'net_lldp',
    'vdirect_commit', 'vdirect_file', 'vdirect_runnable', 'restconf_config', 'restconf_get', 'routeros_command',
    'routeros_facts', 'net_static_route', 'skydive_capture', 'skydive_edge', 'skydive_node', 'slxos_command',
    'slxos_config', 'slxos_facts', 'slxos_interface', 'slxos_l2_interface', 'slxos_l3_interface', 'slxos_linkagg',
    'slxos_lldp', 'slxos_vlan', 'sros_command', 'sros_config', 'sros_rollback', 'net_banner', 'net_logging',
    'net_ping', 'net_system', 'net_user', 'voss_command', 'voss_config', 'voss_facts', 'vyos_banner',
    'vyos_command', 'vyos_config', 'vyos_facts', 'vyos_interface', 'vyos_l3_interface', 'vyos_linkagg', 'vyos_lldp',
    'vyos_lldp_interface', 'vyos_logging', 'vyos_ping', 'vyos_static_route', 'vyos_system', 'vyos_user', 'vyos_vlan'
]

IDENTITY_MODULES = [
    'onepassword_info', 'cyberark_authentication', 'cyberark_user', 'ipa_config', 'ipa_dnsrecord', 'ipa_dnszone',
    'ipa_group', 'ipa_hbacrule', 'ipa_host', 'ipa_hostgroup', 'ipa_role', 'ipa_service', 'ipa_subca', 'ipa_sudocmd',
    'ipa_sudocmdgroup', 'ipa_sudorule', 'ipa_user', 'ipa_vault', 'keycloak_client', 'keycloak_clienttemplate',
    'keycloak_group', 'opendj_backendprop'
]
